### ISSUE TITLE
Glitched visual in revewing page

### ISSUE THREAD

**Issue by CyanGuy111** [beneater/criblate#4]
![image](https://github.com/beneater/criblate/assets/46373872/86633182-6e95-456a-9a97-b4f5c3df94cc)

The description part of reviewing page is glitched as in the screenshot.

I'm using Microsoft Edge as my browser.

**Comment by beneater** [comment]
Problem was the long URLs not wrapping. I fixed the CSS to force-wrap long words so it should look better now. Thanks for reporting!
